AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Truss Data Service API Gateway - Generated for dev"

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: Deployment stage

Resources:
  TrussDataServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "truss-annotation-data-service-api-${StageName}"
      StageName: !Ref StageName
      DefinitionUri: s3://truss-api-automated-deployments/api-specs/0c06a9881538/deployment-ready-dev.yaml
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
      Variables:
        customAuthorizerArn: "arn:aws:lambda:eu-west-2:193757560043:function:truss-annotation-custom-authorizer-dev"
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: false
          LoggingLevel: INFO
          ThrottlingRateLimit: 1000
          ThrottlingBurstLimit: 2000

Outputs:
  ApiGatewayUrl:
    Description: API Gateway Invoke URL
    Value: !Sub "https://${TrussDataServiceApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
    Export:
      Name: !Sub "truss-annotation-data-service-api-${StageName}-url"

  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref TrussDataServiceApi
    Export:
      Name: !Sub "truss-annotation-data-service-api-${StageName}-id"

  Stage:
    Description: Deployment stage
    Value: !Ref StageName
    Export:
      Name: !Sub "truss-annotation-data-service-api-${StageName}-stage"

  CustomAuthorizerArn:
    Description: Custom Authorizer ARN used by this API
    Value: "arn:aws:lambda:eu-west-2:193757560043:function:truss-annotation-custom-authorizer-dev"
    Export:
      Name: !Sub "truss-annotation-data-service-api-dev-custom-authorizer-arn"

