AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Unified annotation-ifl API Gateway with HybridAuth - staging"

Parameters:
  StageName:
    Type: String
    Default: staging
    Description: Deployment stage

Resources:
  UnifiedApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "truss-annotation-intelligent-function-api-${StageName}"
      StageName: !Ref StageName
      DefinitionUri: s3://truss-api-automated-deployments/api-specs/annotation-ifl/bb246e6419ba/deployment-ready-staging.yaml
      EndpointConfiguration:
        Type: REGIONAL
      TracingEnabled: true
      Variables:
        hybridAuthorizerArn: "arn:aws:lambda:eu-west-2:193757560043:function:truss-hybrid-authorizer-staging"
        authorizerStage: !Ref StageName
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          MetricsEnabled: true
          DataTraceEnabled: false
          LoggingLevel: INFO
          ThrottlingRateLimit: 1000
          ThrottlingBurstLimit: 2000

Outputs:
  ApiGatewayUrl:
    Description: Unified API Gateway URL
    Value: !Sub "https://${UnifiedApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}"
    Export:
      Name: !Sub "truss-annotation-intelligent-function-api-${StageName}-url"

  ApiGatewayId:
    Description: API Gateway ID
    Value: !Ref UnifiedApi
    Export:
      Name: !Sub "truss-annotation-intelligent-function-api-${StageName}-id"

  HybridAuthorizerArn:
    Description: Hybrid Authorizer ARN
    Value: "arn:aws:lambda:eu-west-2:193757560043:function:truss-hybrid-authorizer-staging"
    Export:
      Name: !Sub "truss-annotation-intelligent-function-api-${StageName}-authorizer-arn"
