AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Automated annotation service using LangChain for knowledge extraction and text annotation"

Parameters:
  StageName:
    Type: String
    Default: dev
  FunctionName:
    Type: String
  ServiceName:
    Type: String
  CodeS3Bucket:
    Type: String
  CodeS3Key:
    Type: String

Resources:
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "truss-ai-${ServiceName}-${StageName}-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${FunctionName}-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - "arn:aws:secretsmanager:eu-west-2:193757560043:secret:bigquery-service-account*"
                  - "arn:aws:secretsmanager:eu-west-2:193757560043:secret:openAI*"
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/truss-image-processing-*"

  ServiceLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: handler.lambda_handler
      Runtime: python3.11
      Role: !GetAtt ServiceRole.Arn
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Timeout: 300
      MemorySize: 1024
      Layers:
        - "arn:aws:lambda:eu-west-2:193757560043:layer:intelligent-functions-python:5"
      Environment:
        Variables:
          STAGE: !Ref StageName
          SERVICE_NAME: "automated-annotation"
          LAYER_NAME: "aifl"
          DSL_API_BASE_URL: "https://1hc7v2pi9d.execute-api.eu-west-2.amazonaws.com/staging"
          DSL_API_KEY: ""
          ANNOTATION_DSL_API_BASE_URL: "https://xu89om0525.execute-api.eu-west-2.amazonaws.com/staging"
          ANNOTATION_API_KEY: ""
          IFL_API_BASE_URL: "https://ituo0x1fj5.execute-api.eu-west-2.amazonaws.com/staging"
          ANNOTATION_IFL_API_BASE_URL: "https://mabi7l7lvl.execute-api.eu-west-2.amazonaws.com/staging"
          VERTEXAI_PROJECT: "truss-data-science"

  ServiceLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ServiceLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*"

Outputs:
  FunctionArn:
    Description: "ARN of the automated-annotation Service Lambda"
    Value: !GetAtt ServiceLambda.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"

  FunctionName:
    Description: "Name of the automated-annotation Service Lambda"
    Value: !Ref ServiceLambda
    Export:
      Name: !Sub "${AWS::StackName}-FunctionName"
