AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: "Automated annotation service using LangChain for knowledge extraction and text annotation"

Parameters:
  StageName:
    Type: String
    Default: dev
  FunctionName:
    Type: String
  ServiceName:
    Type: String
  CodeS3Bucket:
    Type: String
  CodeS3Key:
    Type: String
  ApiGatewayId:
    Type: String
    Description: API Gateway ID that will invoke this Lambda
    Default: "*"

Resources:
  ServiceApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: !Sub "${FunctionName}-api-key"
      Description: "API Key for automated-annotation service"
      Enabled: true
  ServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "truss-ai-${ServiceName}-${StageName}-role"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub "${FunctionName}-Policy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - "arn:aws:secretsmanager:eu-west-2:193757560043:secret:bigquery-service-account*"
                  - "arn:aws:secretsmanager:eu-west-2:193757560043:secret:openAI*"
                  - "arn:aws:secretsmanager:eu-west-2:193757560043:secret:PineconeAPI-*"
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - "arn:aws:dynamodb:eu-west-2:193757560043:table/model_visual_classifier_nodes"
                  - "arn:aws:dynamodb:eu-west-2:193757560043:table/model_visual_classifier_nodes/index/*"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/truss-image-processing-${StageName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/truss-image-processing-${StageName}/index/*"

  ServiceLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: handler.lambda_handler
      Runtime: python3.11
      Role: !GetAtt ServiceRole.Arn
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Timeout: 300
      MemorySize: 1024
      Environment:
        Variables:
          STAGE: !Ref StageName
          SERVICE_NAME: "automated-annotation"
          SUPPORTED_AUTH_MODES: "cognito,api_key"
          DEFAULT_AUTH_MODE: "cognito"
          BIGQUERY_SECRET_ARN: "arn:aws:secretsmanager:eu-west-2:193757560043:secret:bigquery-service-account-GipBFQ"
          OPENAI_SECRET_ARN: "arn:aws:secretsmanager:eu-west-2:193757560043:secret:openAI-FNAJfl"
          API_KEY_ID: !Ref ServiceApiKey
          COGNITO_USER_POOL_ARNS: "arn:aws:cognito-idp:eu-west-2:193757560043:userpool/eu-west-2_JyaPgaRFW"
          # Vector Classification Configuration
          DYNAMODB_MODEL_TABLE: "model_visual_classifier_nodes"
          PINECONE_SECRET_ARN: "arn:aws:secretsmanager:eu-west-2:193757560043:secret:PineconeAPI-qcy3De"
          VECTORIZATION_API_URL: "https://image-vectorization-api-gpu-94434742359.us-central1.run.app/vectorize"
          VECTORIZATION_API_KEY: ""
          IMAGE_PROCESSING_TABLE: !Sub "truss-image-processing-${StageName}"

  ServiceLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ServiceLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*"

Outputs:
  FunctionArn:
    Description: "ARN of the automated-annotation Service Lambda"
    Value: !GetAtt ServiceLambda.Arn
    Export:
      Name: !Sub "${AWS::StackName}-FunctionArn"

  FunctionName:
    Description: "Name of the automated-annotation Service Lambda"
    Value: !Ref ServiceLambda
    Export:
      Name: !Sub "${AWS::StackName}-FunctionName"

  ApiKeyId:
    Description: API Key ID for private access
    Value: !Ref ServiceApiKey
    Export:
      Name: !Sub "${AWS::StackName}-ApiKeyId"
